apiVersion: v1
kind: Namespace
metadata:
  name: nightwatch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nightwatch
  namespace: nightwatch
  labels:
    app: nightwatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nightwatch
  template:
    metadata:
      labels:
        app: nightwatch
    spec:
      containers:
      - name: nightwatch-back
        image: cisel/nightwatch:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      - name: nightwatch-ui
        env:
        - name: REACT_APP_ACCESS_URL
          value: "http://127.0.0.1:5000"
        image: cisel/nightwatch-ui:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: nightwatch-ui
    namespace: nightwatch
spec:
    ports:
      - name: nightwatch-ui
        port: 443
        targetPort: 3000
    selector:
        app: nightwatch
    type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
    name: nightwatch-back
    namespace: nightwatch
spec:
    ports:
      - name: nightwatch-back
        port: 443
        targetPort: 5000
    selector:
        app: nightwatch
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nightwatch.mysampleurl.com
  namespace: nightwatch
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: nightwatch.mysampleurl.com
      http:
        paths:
          - backend:
              serviceName: nightwatch-ui
              servicePort : 443
    - host: nightwatch-api.mysampleurl.com
      http:
        paths:
          - backend:
              serviceName: nightwatch-back
              servicePort : 443
